name: .NET CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      if: github.event_name != 'pull_request'
      run: |
        dotnet publish src/NetContextServer/NetContextServer.csproj -c Release -o publish/NetContextServer
        dotnet publish src/NetContextClient/NetContextClient.csproj -c Release -o publish/NetContextClient
        
    - name: Upload build artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: net-context-server
        path: publish/ 